### ISSUE TITLE
Nemo transparent

### ISSUE THREAD

**Issue by dan-myles** [cybergaz/hyprconf#1]
Hey!

I couldn't find another way to reach you so I thought this would be the best place. 
I copied some of your dotfiles and they are wonderful. Great job setting things up!

I'm just wondering how did you make your nemo blur so nicely? 
Also what is that overall "theme" for nemo?

Thanks!

**Comment by cybergaz** [comment]
sorry for late reply , i was busy this whole weak i didn't check out for github notifications.

about nemo blur , its just transparency rest of the blur thing is just hyprland's property
and about theme , i use layan theme ( i've written it in my readme also ) ...
